### ISSUE TITLE
fails on simple messages which contain double quotes

### ISSUE THREAD

**Issue by gpflaum** [jenkinsci/google-chat-notification-plugin#45] opened 2023-06-15 19:23 UTC
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Paste the output here
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Linux

### Reproduction steps

Run a Jenkins build with this pipeline script:
```groovy
node {
    String googleWebhook = 'https://chat.googleapis.com/v1/spaces/your-url-here'
    String message = 'The plugin does not handle double quotes: " '
    googlechatnotification message: message, url: googleWebhook;
}
```

### Expected Results

Should send a chat message.

### Actual Results

The Jenkins build log shows that the string sent to the API is improperly quoted, and the Google API returns "Invalid JSON payload"

```
[Pipeline] googlechatnotification
Send Google Chat Notification condition is : true
Final formatted text: { "text": "The plugin does not handle double quotes: " "}
Google Chat post may have failed. Response: {
  "error": {
    "code": 400,
    "message": "Invalid JSON payload received. Expected , or } after key:value pair.\nle double quotes: \" \"}\n                    ^",
    "status": "INVALID_ARGUMENT"
  }
}
 , Response Code: 400
```

### Anything else?

The plugin's [`escapeSpecialCharacter`](https://github.com/jenkinsci/google-chat-notification-plugin/blob/5b27e0a56ff2425ebde2ebc4f3f2618ff720d33d/src/main/java/io/cnaik/service/ResponseMessageUtil.java#L41) function escapes some characters, but not double quotes. (It escapes single quotes, but probably doesn't need to. JSON strings are always double quoted.) Better would be to use a library function like groovy.json.JsonBuilder's toString(), replacing [this code](https://github.com/jenkinsci/google-chat-notification-plugin/blob/5b27e0a56ff2425ebde2ebc4f3f2618ff720d33d/src/main/java/io/cnaik/service/CommonUtil.java#L59) in send() 
```groovy
            json = "{ \"text\": \"" + responseMessageUtil.createTextMessage() + "\"}";
```
with something like this:
```groovy
    def simpleMessage = { text: responseMessageUtil.createTextMessage() }
    String json = groovy.json.JsonBuilder(simpleMessage).toString()
```
and removing use of `replaceJenkinsKeywords` in `createTextMessage()`.

**Comment by rubal033** [comment] 2023-08-05 14:01
On build failure condition, it is adding extra double quotes, working fine for success.

**Comment by Ryudo302** [comment] 2023-09-07 03:20
I was unable to reproduce it with the current code (v.1.7, yet to be released). May it has been fixed by another issue.

**Closed** 2023-09-07 03:21 UTC
Labels: bug
